openapi: "3.0.1"

info:
  title: Container bridge Open REST API Specification
  description: Container bridge Open REST API specification
  version: 1.0.0
# package: agent

servers:
  - url: /

paths:
  /status:
    get:
      tags:
        - private
      summary: Kubernetes readiness and liveness probe endpoint
      responses:
        '200':
          description: successful operation

  /api-docs:
    get:
      tags:
        - public
      summary: List of APIs provided by the service
      responses:
        '200':
          description: OK

  /event/docker/hub:
    post:
      tags:
        - public
      summary: Post Dockerhub artifactory events
      responses:
        '200':
          description: OK
  /event/azure/container:
    post:
      tags:
        - public
      summary: Post Azure Container Registry webhook events
      responses:
        '200':
          description: OK
  /event/quay/container:
    post:
      tags:
        - public
      summary: Post quay Container Registry webhook events
      responses:
        '200':
          description: OK

# oapi-codegen -config ./cfg.yaml ./openapi.yaml
